run:
	runhaskell ./WowIronmanGen.hs

# If you see errors about `Could not find module `System.Random'`,
# then you will need to install the `random` package:
#   $ cabal install random
# Note for Mac Homebrew users:  You can install cabal with:
#   $ brew install cabal-install
